model: /data/mllm/checkpoints/Qwen2.5-VL-7B-Instruct
served-model-name: Qwen/Qwen2.5-VL-7B-Instruct
trust-remote-code: true
tensor-parallel-size: 1
limit-mm-per-prompt.video: 0
gpu-memory-utilization: 0.95
async-scheduling: true
enforce-eager: true
max-num-batched-tokens: 4096
max-num-seqs: 128